"""Init health check

Revision ID: 25910de13178
Revises: 
Create Date: 2022-03-10 12:34:22.665442

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "25910de13178"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checks")
    # ### end Alembic commands ###
