"""Add users

Revision ID: 9cc6ccf1d434
Revises: 25910de13178
Create Date: 2022-03-11 11:49:32.189396

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9cc6ccf1d434"
down_revision = "25910de13178"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
